apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx-deployment
  labels:
    app: test-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-nginx
  template:
    metadata:
      labels:
        app:test-nginx
    spec:
      containers:
      - name: test-nginx-app
        image: nginx:1.14.2
        ports:
        - containerPort: 80